### ISSUE TITLE
cannot print barcodes in the live server

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#170]
## Steps to reproduce
create an analysis request
Generate a barcode, click print button

## Current behavior
the system crushes when clicking the print button

## Expected behavior
the system suppose to print out the barcode immediately after clicking the button

## Screenshot (optional)
![img-20181016-wa0002](https://user-images.githubusercontent.com/12894381/46999811-ff7acb00-d126-11e8-9241-2f978317f594.jpg)

**Comment by xispa** [comment]
Is this still a problem @MoffatMore ?

**Comment by MoffatMore** [comment]
No the problem no longer exists, sorted but the one that is pending is cannot send emails after publishing results

**Comment by xispa** [comment]
Closing this one, then,

RE emails, this is the traceback we get:
```
2018-12-19T08:23:59 ERROR senaite.core {'tshilodikotla-gabs_at_lists.bhp.org.bw': (450, '4.1.7 <bhhrl_at_bhp.org.bw>: Sender address rejected: unverified address: unknown user: "bhhrl"')}
```
At a first glance, seems BHP's mail server is rejecting these emails because the sender email (<bhhrl_at_bhp.org.bw>) and user is not registered there. Coulson is already looking at it and I am awaiting for feedback in case we have to make adjustments in LIMS. Even though, please report the issue to keep track of it.
