### ISSUE TITLE
Verifier is not displayed in some results reports

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#188]
## Steps to reproduce

Order an AR
send to Lab
Receive at reception
Send to point of testing
Receive at point of testing
Process an AR
Verify an AR
Publish the results

## Current behavior
Results report inconsistency. Some verified and released  results are not showing the person who verified the results.
* One of the identifier is 07402AAA2901 , 09604AAA7601

## Expected behavior
results report should be consistent

**Comment by xispa** [comment]
Thanks @MoffatMore , I've just changed the title. Maybe the user who verified the results was not correctly registered as a laboratory contact, will check later.

**Comment by xispa** [comment]
I've done some research. The problem is that the user `dsetlhare` who "verified" + "reported" is registered as a Plone user, but was not assigned in senaite to any Lab Contact. I've fixed this and now should work as expected.

I've also noticed same problem with the following users:

- cralegoreng
- craphaka
- cmdluli
- ckgathi
- fmafoko
- gkenyaditswe
- lkepaletswe
- mmpyane
- ltirelo
- moffat

Looking at the usernames, I'd say all these users were created at the very beginning and the plone user and groups form was used instead of "Lab Contacts" folder view. I managed to assign them to their corresponding Lab Contacts, except the following ones, for which I have not found any candidate:

- cmdluli
- ckgathi
- fmafoko
- lkepaletswe
- ltirelo
- moffat

As a reminder, when you create new lab users, please create them from "Lab Contacts" folder view and once created, use the tab "Login details" to give them access to the system.
