### ISSUE TITLE
Chlamydia trachomatis and Neisseria Gonorrhoea results all come as "NEGATIVE"

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#209]
## Steps to reproduce
Create an analysis request
Send sample to lab
Receive at reception
Send to POT
Receive at POT
Enter results

## Current behavior
Any result entered e.g. POSITIVE appears as "INVALID" before saving but after saving all the results change to "NEGATIVE"

## Expected behavior
The result that is entered should be maintained throughout the transitions

## Screenshot (optional)
<img width="1211" alt="Screenshot 2019-03-13 at 11 48 55" src="https://user-images.githubusercontent.com/41732301/54279831-b1b3a300-459e-11e9-8a65-242c61834185.png">
<img width="1236" alt="Screenshot 2019-03-13 at 12 11 46" src="https://user-images.githubusercontent.com/41732301/54279869-c7c16380-459e-11e9-939f-d2dd10a828f4.png">

**Comment by xispa** [comment]
@cmaphorisa , the problem is that *Chlamydia trachomatis* and *Neisseria gonorrhoea* have same result values for all result options. See screenshot below:

![Captura de 2019-03-13 18-14-52](https://user-images.githubusercontent.com/832627/54300288-d3bc1e00-45bc-11e9-8e84-405057ab0fee.png)

You need to set different result values for all result options. Note that the changes will only have effect to newly created Samples (unless you remove the analyses and add them again through Sample's "Manage Analyses" view).

Related: https://github.com/senaite/senaite.core/issues/1278
