### ISSUE TITLE
Delivery checklist should have a container type

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#222]
## Steps to reproduce
#217

**Comment by xispa** [comment]
Please, update the description (Steps to reproduce, Current behavior, expected behavior) of this issue accordingly instead of linking to a different issue. Think about the issue tracker, along with pull requests, as the documented history of the project. Future readers will appreciate this, specially if something goes wrong or there is a bug that, somehow, could be related with one of the issues or PRs. Thanks.
