### ISSUE TITLE
Cannot change state of an analysis request from shipped to receive at reception

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#240]
## Steps to reproduce
order an AR
send to lab
receive at reception

## Current behavior
Some analysis request are unable to be received at reception, the system throws a warning that no changes made
SID's for analysis request that are unable to be received at reception

08502ADM64
08502ADM62
08508AAA83
08504AAB40

**Comment by xispa** [comment]
@MoffatMore I've seen a suspicious error in the log related with a database conflict (this happens when two people try to modify/transition same object at same time), but nothing else.

I've tried with `08502ADM64` and it worked to me (I've transitioned this sample to "received" status). Can you tell lab people to try again with the rest of specimens?
