### ISSUE TITLE
For Sample ID for a partitions that are not have the same sample type as the parent sample sample are not flowing the sample id format expected

### ISSUE THREAD

**Issue by ckgathi** [bhp-lims/bhp.lims#254]

**Comment by xispa** [comment]
Hi @coulson this ticket is poorly explained. I haven't experienced problems with setting the sample type to a given partition while partitioning. Please provide more details by filling the issue template sections

**Comment by ckgathi** [comment]
I assumed since we discussed this in the call you would understand but i will update with more details in a bit

**Comment by ckgathi** [comment]
Sample Identifier Example

The sample identifier is broken down in the following format:

An example using participant identifier: 085-40990496-3
Requisition Identifier: 997N2P4

Primary Sample will have the identifier: 08540997N2P40201 (Barcode Number)

085: Study/ Protocol Number
40:  Site Code; 40 for Gaborone
997N2P4:  As above, Requisition Identifier for the sample (unique per sample)
02: Sample Type, 02 for whole blood
01: Sequence, Primary sample always 01

Aliquots/ Partitions for sample 08540997N2P40201; analysis request is 1-hour fasting Glucose:

08540997N2P4: See Above
32: Sample Type, 32 for plasma
02: Sequence, second aliquot/partition generated. 

The Sample Types for the Tshilo Dikotla (085) study:

1.	'Whole Blood', 'WB', '02',
2.	'Plasma', 'PL', '32',
3.	'Buffy Coat', 'BC', '16',
4.	'PBMC', 'PBMC', '31',
5.	'Serum', 'SERUM', '06'
6.	UNS (RPMI) -72
7.	BCG - 73
8.	ESAT-6/CFP-74
9.	PHA-74
10.	Wba-pl-hep 77
11.	UNS (RPMI) – CEL 81
12.	BCG - CEL 82
13.	ESAT-6/CFP – CEL 83
14.	PHA – CEL 84
15.	

Sample Identifier Recommended
Participant identifier: External
Requisition Identifier:  99AAA (5-alpha-numeric) – unique within study

----------- JORDI -------->

Much better if the numeric part is at the end. An alpha-numeric code like AAA00 can generate:

 99 * 26³ = 1.740,024 different Requistion IDs


Since the relationship between a requisition form and a Primary Sample is ~1, I'd suggest to assume the requisition ID = Primary Sample ID. Thus, I'd add the study code, as well as the sample type. E.g:

08573AAA0102 >>08577AAA0102 wba-pl-hep uns >>08581AAA0102 wba-cel uns
08574AAA0103>>08578AAA0102 wba-pl-hep bcg>> 08578AAA0102 wba-cel bcg

08575AAA0104>>>>08579AAA0102 wba-pl-hep esat
08576AAA0105>>>>08580AAA0102 wba-pl-hep  pha



Where:
085: Study ID
02: Sample Type (Whole blood)
AAA01: (Initial) Requisition ID
01: Primary sample ID

Then, the system would be able to generate 1.740,024 different Sample IDs/Requisition IDs for each study+sample type intersection, and 98 different partitions for each Primary Sample (would a maximum of 8 partitions per Primary Sample would be enough?).

The ID of the first partition (of Serum Sample Type = 06) from the Sample above would look like:

08506AAA0102

And the ID of another partition (of Plasma = 32) from the Sample above, would look like

08532AAA0103

Changing both the sample type and last two digits allow us to have more than one partition with same sample type for each Primary Sample. Note that while the sample type and the last 2 digits change, the (initial) requisition ID and study ID remain untouched. 

Additional note

You could add the site code within the study ID and the Sample Type, 

0854002AAA0101

but I am afraid the code will be too long for the barcode to fit in small labels. In fact, we should test how many different characters can fit in the smallest label you'd like to use (the most compact barcode encoding is 3of9).

See barcode samples below ---





The previous one encoded in 3of9:





And without the Study ID:







We are assuming here that every single Sample will have only 1 Analysis Request (secondary ARs are not allowed, we use new partitions machinery instead).

<---------------- JORDI

Study code:  085 (from BHP085 study code)
Sample type: 02 “whole blood” from the list of sample type codes
Aliquot number: serial



Use of R1 or R2 within Senaite??

085997NPA0201 ---- whole blood
085997NPA3201 ----- Plasma ALQ 01
085997NPA3202 ----- Plasma ALQ 02

**Comment by xispa** [comment]
@ckgathi I've been struggling on adding the "01" suffix in the primary sample without success. The problem is that this suffix is somehow "hardcoded", so when creating new primary samples, the system recognizes this prefix as part of sequence numbering. Hence, the alpha number is not increased in one unit and eventually we end up with id conflicts. In summary, I kept the schema we agreed for first-level partitions, except that the primary sample will not end with "01":

![Captura de 2019-06-26 15-18-47](https://user-images.githubusercontent.com/832627/60183231-29dc6680-9826-11e9-8576-702d830ff3c9.png)

In the screenshot above:

`09202AAJ60` (primary sample):
  - `09`: study id
  - `202`: sample type
  - `AAJ60`: sequential alphanumber

`09202AAJ6002`: first partition, same sample type as primary
`09222AAJ6003`: second partition, different sample type (Plasma EDTA) from primary
`09222AAJ6004`: third partition, different sample type (Plasma EDTA) from primary

Note `02`, `03` and `04` suffixes are an incremental number starting from 2 (we expected to use `01` for the primary).

Will report back with more info as soon as I have secondary partitions (partitions from partitions) id schema in place.

**Comment by ckgathi** [comment]
Noted, 

you mentioned this will be in the pilot instance yesterday and since its not, whats the tentative date now considering challenges you are having?

**Comment by xispa** [comment]
@ckgathi this is in the pilot instance already
